dist: xenial

services:
  - postgresql
addons:
  chrome: stable
  postgresql: "9.4"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
